name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  TFX_GPG_PASSWORD: ${{ secrets.TFX_GPG_PASSWORD }}
  TFX_CI_USERNAME: ${{ secrets.TFX_CI_USERNAME }}
  WEBSITE_DEPLOY_PATH: '/opt/tfx/website'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Fetch sources
        uses: actions/checkout@v3

      - name: Configuration
        shell: bash
        run: |
          source .github/config.sh

#      - name: Generate HTML from Markdown
#        uses: ldeluigi/markdown-docs@latest
#        with:
#          src: web
#          dst: build

      - name: Generate HTML from Markdown
        uses: natescherer/markdown-to-html-with-github-style-action@v1.1.0
        with:
          path: index.md
          outputpath: build

#      - name: Generate HTML from Markdown
#        uses: ZacJW/markdown-html-action@1.1.0
#        with:
#          input_files: '[["*.md"]]'
#          output_files: '["build"]'

      - name: Deploy
        run: |
          ssh -t ${{env.TFX_CI_USERNAME}}@soderquist.net "mkdir -p ${{env.WEBSITE_DEPLOY_PATH}};" 2>&1
          if [ $? -ne 0 ]; then exit 1; fi
          scp -r -B build/* ${{env.TFX_CI_USERNAME}}@soderquist.net:${{env.WEBSITE_DEPLOY_PATH}} 2>&1
          if [ $? -ne 0 ]; then exit 1; fi
